#!/usr/bin/env python3
"""
Extract Chinese vocabulary from HSK Anki .apkg files and generate a Kotlin source file.

Usage: python3 scripts/extract_anki_vocab.py
Run from the project root directory.
"""

import os
import re
import sqlite3
import tempfile
import unicodedata
import zipfile

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(
    PROJECT_ROOT,
    "app/src/main/java/net/kollnig/reddblockandroid/data/ChineseVocabulary.kt",
)

APKG_FILES = [
    ("HSK_1_Mandarin__Characters_Pinyin_Sentences__Audio.apkg", 1),
    ("HSK_2_Mandarin__Characters_Pinyin_Sentences__Audio.apkg", 2),
    ("HSK_3_Mandarin__Characters_Pinyin_Sentences__Audio.apkg", 3),
    ("HSK_4_Mandarin__Characters_Pinyin_Sentences__Audio.apkg", 4),
    ("HSK_5_Mandarin__Characters_Pinyin_Sentences__Audio.apkg", 5),
]

# Field indices inside the \x1f-separated `flds` column (model: "HSK Fav")
F_SIMPLIFIED = 1
F_PINYIN = 3
F_MEANING = 5


def strip_html(text: str) -> str:
    text = re.sub(r"<[^>]+>", "", text)
    text = text.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
    return text.strip()


def normalize_pinyin(pinyin: str) -> str:
    """Strip tone diacritics and spaces, normalize to lowercase for matching.

    Removes all spaces so that both "women" and "wo men" match the same key.
    """
    decomposed = unicodedata.normalize("NFD", pinyin.strip().lower())
    without_tones = re.sub(r"[\u0300-\u036f]", "", decomposed)  # combining diacritics
    # Also strip trailing tone numbers (e.g. "wo3" -> "wo")
    without_tones = re.sub(r"(\w)(\d)", r"\1", without_tones)
    # Remove all spaces — "wo men" and "women" should both become "women"
    return without_tones.replace(" ", "")


def first_pinyin_variant(pinyin: str) -> str:
    """For entries like 'ā, á, ǎ, à, a', return just the first variant."""
    if "," in pinyin:
        return pinyin.split(",")[0].strip()
    return pinyin.strip()


def shorten_meaning(meaning: str) -> str:
    """Take only the first definition to keep display concise."""
    meaning = strip_html(meaning)
    # Split on semicolon and take first
    parts = meaning.split(";")
    result = parts[0].strip()
    # Cap length
    if len(result) > 60:
        result = result[:57] + "..."
    return result


def extract_words(apkg_path: str, hsk_level: int) -> list[dict]:
    words = []
    with tempfile.TemporaryDirectory() as tmpdir:
        with zipfile.ZipFile(apkg_path, "r") as zf:
            zf.extractall(tmpdir)

        # Prefer anki21 format
        db_path = os.path.join(tmpdir, "collection.anki21")
        if not os.path.exists(db_path):
            db_path = os.path.join(tmpdir, "collection.anki2")

        conn = sqlite3.connect(db_path)
        rows = conn.execute("SELECT flds FROM notes").fetchall()
        conn.close()

        for row in rows:
            fields = row[0].split("\x1f")
            if len(fields) <= F_MEANING:
                continue

            character = fields[F_SIMPLIFIED].strip()
            pinyin_raw = first_pinyin_variant(fields[F_PINYIN])
            meaning = shorten_meaning(fields[F_MEANING])

            if not character or not pinyin_raw or not meaning:
                continue

            words.append(
                {
                    "character": character,
                    "pinyin": pinyin_raw,
                    "pinyin_normalized": normalize_pinyin(pinyin_raw),
                    "meaning": meaning,
                    "hsk_level": hsk_level,
                }
            )

    return words


def escape_kotlin_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def generate_kotlin(all_words: list[dict]) -> str:
    lines = []
    lines.append("package net.kollnig.reddblockandroid.data")
    lines.append("")
    lines.append("// Generated by scripts/extract_anki_vocab.py from HSK 1-3 Anki decks.")
    lines.append("// Do not edit manually.")
    lines.append("")
    lines.append("data class ChineseWord(")
    lines.append("    val character: String,")
    lines.append("    val pinyin: String,")
    lines.append("    val pinyinNormalized: String,")
    lines.append("    val meaning: String,")
    lines.append("    val hskLevel: Int,")
    lines.append(")")
    lines.append("")
    lines.append("val CHINESE_VOCABULARY: List<ChineseWord> = listOf(")

    for w in all_words:
        c = escape_kotlin_string(w["character"])
        p = escape_kotlin_string(w["pinyin"])
        pn = escape_kotlin_string(w["pinyin_normalized"])
        m = escape_kotlin_string(w["meaning"])
        h = w["hsk_level"]
        lines.append(f'    ChineseWord("{c}", "{p}", "{pn}", "{m}", {h}),')

    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main():
    all_words = []
    seen_chars = set()

    for filename, level in APKG_FILES:
        apkg_path = os.path.join(PROJECT_ROOT, filename)
        if not os.path.exists(apkg_path):
            print(f"Warning: {filename} not found, skipping")
            continue

        words = extract_words(apkg_path, level)
        # Deduplicate by character (keep first/lowest HSK level)
        for w in words:
            if w["character"] not in seen_chars:
                seen_chars.add(w["character"])
                all_words.append(w)

        print(f"HSK {level}: {len(words)} entries ({len(words) - (len(words) - len([w for w in words if w['character'] in seen_chars]))} new)")

    print(f"Total unique entries: {len(all_words)}")

    kotlin_source = generate_kotlin(all_words)
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(kotlin_source)

    print(f"Generated: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
